# Generated by Django 4.1.7 on 2023-03-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-id',)},
        ),
    ]
